name: Desplegar infraestructura

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform apply, AZ destroy o UpgradeContainerApps'
        required: true
        default: 'apply'
        type: choice
        options:
          - apply
          - destroy
          - container_app_only

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      RG_NAME: rg-cicd-terraform-app-logisticaJJR    
    steps:
      - uses: actions/checkout@v3

      - name: Check if secret exists
        run: |
          if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
            echo "Secret NOT available"
          else
            echo "Secret available"
          fi

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: List accessible Resource Groups
        run: az group list --output table

      - name: List resources in specific RG
        run: |
          echo "Listing all resources in Resource Group: $RG_NAME"
          az resource list --resource-group $RG_NAME --output table

      - name: AZ Destroy (Delete Container Apps)
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          az containerapp delete \
            --name frontend-app \
            --resource-group $RG_NAME \
            --yes
          az containerapp delete \
            --name backend-app \
            --resource-group $RG_NAME \
            --yes

      - name: AZ Destroy (Delete Container App Environment)
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          az containerapp env delete \
            --name demo-cae \
            --resource-group $RG_NAME \
            --yes \
            --verbose

      - name: AZ Destroy (Delete Virtual )
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: |
          az network vnet delete \
            --name demo-vnet \
            --resource-group $RG_NAME || true

      - name: Setup Terraform
        if: ${{ github.event.inputs.action == 'apply' || github.event.inputs.action == 'container_app_only' }}      
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        if: ${{ github.event.inputs.action == 'apply' || github.event.inputs.action == 'container_app_only' }}      
        run: terraform init

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          terraform apply -auto-approve
          ls -la

      - name: Terraform Apply Container App (Frontend y Backend)
        if: ${{ github.event.inputs.action == 'container_app_only' }}
        run: | 
          terraform import azurerm_container_app_environment.demo_cae \
          /subscriptions/69633081-5735-434d-8ccd-9c14b4016ad1/resourceGroups/rg-cicd-terraform-app-logisticaJJR/providers/Microsoft.App/managedEnvironments/demo-cae
          terraform import azurerm_container_app.backend \
          /subscriptions/69633081-5735-434d-8ccd-9c14b4016ad1/resourceGroups/rg-cicd-terraform-app-logisticaJJR/providers/Microsoft.App/containerApps/backend-app
          terraform import azurerm_container_app.frontend \
          /subscriptions/69633081-5735-434d-8ccd-9c14b4016ad1/resourceGroups/rg-cicd-terraform-app-logisticaJJR/providers/Microsoft.App/containerApps/frontend-app
          terraform apply -target=azurerm_container_app.frontend -auto-approve
          terraform apply -target=azurerm_container_app.backend -auto-approve
        
      - name: Save Terraform state file
        if: ${{ github.event.inputs.action == 'apply' }}
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: ./terraform.tfstate