name: Terraform Deploy POC

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'apply o destroy'
        required: true
        default: 'apply'

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Check if secret exists
      run: |
        if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
          echo "Secret NOT available"
        else
          echo "Secret available"
        fi
        
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: List accessible Resource Groups
      run: az group list --output table
 
    - name: Delete Container App
      run: |
        az containerapp delete \
          --name frontend-app \
          --resource-group rg-cicd-terraform-app-logisticaJJR \
          --yes
        az containerapp delete \
          --name backend-app \
          --resource-group rg-cicd-terraform-app-logisticaJJR \
          --yes          

    - name: Delete Container App Environment
      run: |
        az containerapp env delete \
          --name demo-cae \
          --resource-group rg-cicd-terraform-app-logisticaJJR \
          --yes \
          --verbose

    - name: Delete Virtual Network
      run: |
        az network vnet delete \
          --name demo-vnet \
          --resource-group rg-cicd-terraform-app-logisticaJJR || true
 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Download previous state
      uses: actions/download-artifact@v4
      with:
        name: terraform-state
        path: ./terraform
          
    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply/Destroy
      run: |
        if [ "${{ github.event.inputs.action }}" == "apply" ]; then
          terraform apply -auto-approve
        else
          terraform destroy -auto-approve
        fi
        
    - name: Upload state (90 days)
      uses: actions/upload-artifact@v4
      with:
        name: terraform-state
        path: ./terraform/terraform.tfstate        